//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPOS.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_TRANSLATION
    {
        public int productId { get; set; }
        public int languageId { get; set; }
        public string nameProduct { get; set; }
        public string description { get; set; }
    
        public virtual LANGUAGE LANGUAGE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
