//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPOS.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBCATEGORY
    {
        public int idSubcategory { get; set; }
        public int parentCategory { get; set; }
        public int childCategory { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual CATEGORY CATEGORY1 { get; set; }
    }
}
