//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPOS.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACTION()
        {
            this.PAYMENTs = new HashSet<PAYMENT>();
            this.TRANSACTION_DETAILS = new HashSet<TRANSACTION_DETAILS>();
        }
    
        public int idTransaction { get; set; }
        public System.DateTime transactionDate { get; set; }
        public decimal total { get; set; }
        public bool isClose { get; set; }
        public bool isCanceled { get; set; }
        public bool isReturn { get; set; }
        public int vendorId { get; set; }
        public int terminalId { get; set; }
        public int languageId { get; set; }
        public int shopId { get; set; }
        public int customerId { get; set; }
        public int ticketId { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual LANGUAGE LANGUAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT> PAYMENTs { get; set; }
        public virtual SHOP SHOP { get; set; }
        public virtual TERMINAL TERMINAL { get; set; }
        public virtual TICKET TICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTION_DETAILS> TRANSACTION_DETAILS { get; set; }
        public virtual USER USER { get; set; }
    }
}
